import { StatusBar } from "expo-status-bar";
import { useEffect, useState } from "react";
import {
  Button,
  ImageBackground,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Image,
  Input,
  KeyboardAvoidingView,
  Dimensions,
  ScrollView,
  Alert
} from "react-native";
// import Calendar from '../Components/calendar';
import DropDownPicker from "react-native-dropdown-picker";

const screenWidth = Dimensions.get('window').width
const screenHeight = Dimensions.get('window').height

const styleWiseProcess = {
  Tee: [
    "Shoulder join",
    "Sleeve pair & set",
    "Neck rib make & measure cut",
    "Neck rib servicing 1st",
    "Body mark for neck rib attach",
    "Back neck tape end tack & trim",
    "Sleeve hem",
    "Sleeve & bottom  hem join tack",
    "Spot & stitcker remove",
    "Back deviding join",
    "Back deviding join topstitch",
    "Half moon iron & scissoring",
    "Patch label mark & attach",
    "Body mark for moon attach",
    "Moon attach",
    "Shoulder topstitch",
    "Sleeve panel join 1st part with panel matching",
    "Sleeve panel join 2nd part with panel matching",
    "Sleeve panel 1st part topstitch",
    "Sleeve panel 2nd part topstitch",
    "Sleeve tack to body (Point match)",
    "Neck & sleeve cuff measure & cut",
    "Neck rib join & topstitch",
    "Sleeve cuff join &  topstitch",
    "Neck rib attach ( Stripe )",
    "Back neck tape attach",
    "Back neck end tack & trim",
    "Sleeve cuff attach",
    "Bottom servicing",
    "Tack at bottom hem ",
    "Bottom  hem join tack",
    "Neck rib servicing 2nd",
    "Neck rib stitch open & end tack",
    "Binding cutter & shoulder scissoring",
    "Front neck topstitch",
    "Back neck tape attach (stripe)",
    "Side seam (stripe)",
    "Sleeve hem ( stripe)",
    "Front neck topstitch security tack",
    "Panel matching ",
    "Sleeve attach",
    "Neck rib V make & mark",
    "Neck rib end tack",
    "Neck rib iron",
    "V tack to body",
    "Neck rib attach",
    "Main label mark & attach",
    "Back neck tape close with loop",
    "Country label attach",
    "Flag label attach",
    "Side seam with body set",
    "Care label attach",
    "Bottom hem",
    "V security tack"
  ],
  Polo: [
    "Body mark  for placket attach",
    "Placket iorn & mark",
    "Half moon iron & scissoring",
    "Half moon attach",
    "Moon topstitch ",
    "Placket attach & edge close",
    "Nose tack & Placket open ",
    "Binding at placket & role make",
    "Shoulder join & front back set",
    "Mark for collar attach",
    "Placket o/l",
    "Collar tack to body",
    "Collar attach",
    "Back neck tape measure & mark for lbl attach",
    "Back neck tape attach",
    "Back neck tape close with label/loop",
    "Top placket inner top stich",
    "Under placket inner top stitch",
    "Under placket edge top stitch",
    "Placket tack to body",
    "Make placket box",
    "Sleeve pair & set",
    "Sleeve attach",
    "Sleeve cuff measure & cut & trim",
    "Sleeve cuff join & topstitch & mark",
    "Sleeve cuff attach",
    "Placket base o/l",
    "Tack at bottom hem",
    "Neck label or slim fit lbl mark & attach",
    "Mark for sleeve cuff attach",
    "Bottom join tack",
    "Make button hole",
    "Mark for button attach",
    "Insert button ",
    "Spot & sticker remove & body set",
    "Callar servicing & mark",
    "Main label  mark & attach",
    "Body mark  for moon attach",
    "Sleeve cuff edge ol",
    "Moon iron & scissoring",
    "Moon mark & attach",
    "Placket attach & mark",
    "Placket open ",
    "Shoulder scissoring,sleeve pair & set",
    "Collar servicing & iron",
    "Fit label iron",
    "Placket base tack & scissoring",
    "Bottom servicing",
    "Sleeve cuff join & topstitch & mark for attach",
    "Bottom join tack & Care label attach ",
    "Fit label attach",
    "Button insert",
    "Button wrapping",
    "Placket iron for topstitch",
    "Placket attach & rawstitch ",
    "Top placket edge topstich ",
    "Side slit ol",
    "Care lbl make & attach ",
    "Collar stand hem & set",
    "Collar stand attach",
    "Collar stand middle topstitch",
    "Collar stand attach 1st & mark",
    "Collar draw & collar edge trim & iron",
    "Collar attach",
    "Main label make",
    "Neck loop mark & attach",
    "Collar close ",
    "Side slit open close",
    "Bar tack at side slit ",
    "Country label attach & false stitch open",
    "Mark for button hole & attach",
    "Button attach",
    "Panel matching  & body mark",
    "Shoulder topstitch",
    "Back neck tape attach",
    "Placke tack to body",
    "Slim fit or main lable & placket iron for button",
    "Mark for slim fit lor main abel attach",
    "Slim fit or main label attach",
    "Main label attach",
    "Armhole topstitch",
    "Bottom hem",
    "Side seam  with body set",
    "Placket base tack & trim",
    "Side slit open tack with tape & stitch open",
    "Side slit tape minner mark & make",
    "Side slit tape fold & tack",
    "Side slit tape attach",
    "Side slit tape close",
    "Body mark for moon attach",
    "Half moon  attach",
    "Body middle mark for placket attach",
    "Placket mark & iron",
    "Placket attach ",
    "Placket open",
    "Nose tack",
    "Collar  attach",
    "Hidden placket mark cut & iron",
    "Bottom hem with side slit tape make",
    "Sleeve open  tack",
    "Care lbl make & attach",
    "Shoulder loop attach",
    "Armhole cross tack",
    "Side slit tape minner make,& mark "
  ],
  "Sweat Shirt": [
    "Panel matching & shoulder join",
    "Shoulder loop attach",
    "Side seam with body set",
    "Sleeve hem",
    "Bottom hem",
    "Bottom & sleeve security Tack",
    "Armhole cross tack",
    "Body set & output",
    "Front cut & sew tack to body",
    "Front cut & sew topstitch & mark",
    "Front cut & sew topstitch end tack ",
    "Over stitch open",
    "Sleeve attach at front & Sleeve pair & set",
    "Sleeve attach at back & Sleeve pair & set",
    "Armhole topstitch front & back",
    "Back neck tape attach & Mark for back neck tape attach & trim",
    "Mark for label close",
    "Neck or fit label attatch with mark",
    "Mark for bottom rib attatch",
    "Front cut & sew attach",
    "Front cut & sew topstitch end tack & Over stitch open",
    "Mark for moon attach",
    "Half moon edge ol & iron",
    "Half moon false attatch",
    "Half moon topstitch",
    "False stitch open",
    "Neck rib attach",
    "Armhole cut & sew tack to body",
    "Armhole cut & sew attach",
    "Armhole cut & sew topstitch & mark",
    "Armhole cut & sew topstitch end tack  & Over stitch open",
    "Mark & punch for hole at armhole",
    "Hole at armhole",
    "Armhole topstitch  end security tack",
    "Shoulder join",
    "Neck rib join,fold & mark",
    "Neck rib iron",
    "Mark for beck neck attach & trim",
    "Back neck tape attach",
    "Back neck tape close  with loop/label",
    "Sleeve pair & set",
    "Side seam  ",
    "Sleeve cuff join &fold & mark",
    "Sleeve cuff inside ack",
    "Sleeve cuff attach",
    "Bottom rib join & body mark",
    "Bottom rib inside tack",
    "Bottom rib servicing",
    "Bottom rib attach",
    "Counrty label attach & false stitch open",
    "Spot & sticker remove",
    "Front neck cut & sew tack to body or attach",
    "Front neck cut & sew attach",
    "Front neck cut & sew topstitch ",
    "Front neck cut & sew topstitch end tack & over stitch open",
    "Shoulder join topstitch ",
    "Neck rib servicing 1st",
    "Neck rib servicing 2nd",
    "Body mark for neck rib attach",
    "Neck rib tack to body",
    "Binding cutter & shoulder scissoring",
    "Side seam topstitch",
    "Sleeve side seam",
    "Armhole topstitch ",
    "Sleeve cuff topstitch",
    "Bottom rib topstitch",
    "Sleeve & bottom join tack",
    "Shoulder join & front back set",
    "Main label  false attach",
    "Bartack at main label",
    "Side cut & sew attach 1st",
    "Side cut & sew attach 2nd & mark",
    "Side cut & sew attach topstitch 1st",
    "Side cut & sew attach topstitch 2nd",
    "Sleeve side seam topstitch",
    "Shoulder scissorings,Sleeve pair & set ",
    "Bottom rib join,fold ",
    "Front neck topstitch end security tack & stitch open",
    "False size label attach",
    "Country label attach",
    "Body mark for rib attach",
    "Panel matching",
    "Front neck topstitch",
    "Main label mark & attach",
    "Flag label attach",
    "Mark for sleeve attach",
    "Sleeve attach",
    "Armhole topstitch (Round)",
    "Care label attach"
  ],
  Jacket: [
    "Pocket topstitch",
    "Pocket topstitch end security tack & over stitch open",
    "Sleeve attach at front & Sleeve pair & set",
    "Sleeve attach at back & Sleeve pair & set",
    "Bottom rib facing cut mark &  edge servicing",
    "Bottom rib servicing",
    "Bottom rib facing attach",
    "Bottom rib facing attach topstitch",
    "Hood upper  & lower two part join topstitch",
    "Zipper topstitch",
    "Pocket hem ( 2M/C 1 OP )",
    "Pocket attach & close",
    "Front open for zipper attach",
    "Shoulder loop attach & Flag label attach & fit label join",
    "Sleeve cuff join fold & mark",
    "Bottom rib & body mark",
    "Bottom rib attach",
    "Loop tack at hood inside & hood mouth close ",
    "Mark for hood attach & pair",
    "Zipper end tack & trim",
    "Zipper & body mark for attach",
    "Zipper attach",
    "Rawedge trim",
    "Binding attach at zipper",
    "Hood upper close",
    "Hood lower close",
    "Bottom rib lower close",
    "Back neck tape close  with label",
    "Hood hem security tack",
    "Care label make & attach ",
    "Drawcord insert",
    "Drawcord middle tack",
    "Front cut & sew tack to body",
    "Front cut & sew attach",
    "Front cut & sew topstitch & mark",
    "Front cut & sew topstitch end tack & Over stitch open",
    "Body mark for pocket attach",
    "Pocket edge o/l ",
    "Pocket hem ",
    "Pocket iron & scissoring",
    "Pocket attach (Inner & top)",
    "Pocket attach topstitch",
    "Bartack at pocket & Over stitch open",
    "Mark for moon attach",
    "Half moon edge ol & iron",
    "Half moon false atatch",
    "Half moon topstitch",
    "False stitch open",
    "Shoulder join & Panel matching",
    "Shoulder loop attach",
    "Side seam with body set",
    "Armhole cut & sew tack to body",
    "Armhole cut & sew attach",
    "Armhole cut & sew topstitch & mark",
    "Armhole cut & sew topstitch end tack  & Over stitch open",
    "Mark & punch for hole at armhole",
    "Hole at armhole",
    "Sleeve side seam",
    "Sleeve attach & Sleeve pair & set",
    "Armhole topstitch ",
    "Armhole topstitch  end security tack",
    "Hood upper  & lower two part join",
    "Hood upper topstitch",
    "Hood two part edge topstitch",
    "Mark & punch for hole at hood",
    "Hole at hood",
    "Loop tack & hood inside & hood mouth close",
    "V mark & make",
    "Hood tack to body",
    "Back neck tape attach & Mark for back neck tape attach & trim",
    "Back neck tape close with label & Mark for label close",
    "Bottom rib  join & inside tack",
    "Bottom rib servicing & Mark for bottom rib atatch",
    "Bottom rib  attach",
    "Sleeve cuff join &  inside tack  fold ",
    "Care label make & attach",
    "Drawcord insert & middle tack",
    "Pocket edge ol",
    "Pocket hem",
    "Inside mark for runstitch & pocket attach",
    "Inside  part runstitch ",
    "Pocket attach with inside part",
    "Pocket attach with inside part bottom area",
    "Front pocket iron",
    "Mark for yoke attach at front",
    "Front yoke attach OL",
    "Back deviding join finish tack",
    "Back deviding join ",
    "Back deviding join topstitch",
    "Shoulder join & front & back",
    "Shoulder join topstitch",
    "Bottom rib edge servicing & cut mark",
    "Mark for bottom rib attach",
    "Bottom rib attach & body mark",
    "Bottom rib fold tack with front part",
    "Bottom rib upper close",
    "Side seam topstitch ",
    "Sleeve side",
    "Shoulder scissoring,Sleeve pair & set",
    "Mark for sleeve attach",
    "Sleeve attach(tube)",
    "Armhole topstitch(tube)",
    "Armhole topstitch security tack",
    "Sleeve cuff join ,  inside tack & fold & mark",
    "Hood upper lower two part join ( 2 m/C 1 OP)",
    "Hood upper & lower two part join topstitch ( 2 m/C 1 OP)",
    "Mark &  punch for hood at hole",
    "Hood mark & attach",
    "Back neck contrast tape make & iron",
    "Back neck contrast tape attach",
    "Main label mark& attach",
    "Care lbl attach & Country label attach",
    "Sleeve security tack & false stitch open",
    "Drawcord insert ",
    "Bartack at pocket",
    "Mark for bottom tack",
    "Front yoke tack  for attach",
    "Bartack at back deviding topstitch end & over stitch open",
    "Bartack at hood",
    "Side seam matching tack ",
    "Pocket binding stitch open & tack",
    "Pocket rib make & mark & iron",
    "Pocket rib attach &Mark for pocket attach",
    "Pocket 1st part attach & 2nd part attach",
    "Pocket rib open & ol",
    "Pocket rib tack to body & mark",
    "Pocket & pocket rib o/l & close",
    "Binding attach at pocket & role make",
    "Shoulder scissoring,sleeve  pair & set",
    "Upper & lower pocket tack for side",
    "Side seam",
    "Hood 3 part join ",
    "Binding at hood",
    "Binding close at hood",
    "Zipper  faching o/l",
    "Hood panel  edge o/l & mark",
    "Hood panel two part  join",
    "Hood two part edge join",
    "Binding at hood edge",
    "Mark &  punch for hood hole",
    "Hood hole make",
    "Hood hem  with binding close",
    "Hood servicing with faching",
    "Hood  middle mark & match",
    "Back neck tape attach,& lbl mark ",
    "Back neck tape close with lbl & main label mark & attach",
    "Binding role make",
    "Care lbl attach (one part) & main label make & attach",
    "Country label attach & neck loop make & attach",
    "Sleeve cuff join ,fold & mark",
    "Bottom rib measure cut & servicing for rib attach",
    "Bottom rib edge o/l",
    "Bottom rib attach & mark",
    "Pocket edge close with bottom",
    "Zipper faching fold & tack at bottom ",
    "Zipper faching attach",
    "Zipper end tack  & mark",
    "Zipper & body mark",
    "Zipper attach with faching",
    "Zipper rawedge trim",
    "Zipper topstitch with faching",
    "Zipper faching upper close",
    "Bottom rib edge close",
    "Pocket mark & tack to faching",
    "Drawcord measure cut & insert",
    "Front open for zipper attach (Iron & DN)",
    "Bar tack at hood & pocket",
    "Security tack at sleeve & zipper faching end tack",
    "Back neck tape inside edge close",
    "Pocket mouth servicing &servicing with body &  (OL & SN)",
    "Half moon iron & scissoring",
    "Body middle mark for moon attach & pocket attach",
    "Half moon attach & close",
    "Half moon mouth close & scissoring",
    "Pocket 1st part attach ",
    "Pocket rawstitch & Pocket open",
    "Pocket edge topstitch",
    "Pocket bag servicing at side",
    "Binding attach at pocket",
    "Pocket 2nd part tack to body",
    "Panel matching",
    "Shoulder join",
    "Sleeve pair & set",
    "Neck rib join & fold",
    "Neck rib join inside tack",
    "Neck rib join servicing 1st",
    "Neck rib join servicing 2nd",
    "Body,rib mark for rib attach",
    "Neck rib attach",
    "Back neck tape end tack & trim",
    "Main label make",
    "Tack for side seam &Back & front part set for side",
    "Side seam  & Side slit ol",
    "Sleeve cuff join& fold",
    "Bottom rib edge servicing & mark",
    "Zipper end tack & trim & mark",
    "Side slit open tack",
    "Zipper mark & attach",
    "Zipper raw edge trim",
    "Side zipper edge ol",
    "Side zipper rawstitch",
    "Zipper upper &lower close",
    "Country label attach & false stitch open",
    "Bartack at side pocket",
    "Side seam  security tack ( Open area )",
    "Care lbl attach",
    "Shoulder join & front back set",
    "Shoulder topstitch & trim",
    "Shoulder scissorings,Sleeve pair & set",
    "Sleeve attach ",
    "Hood  upper & lower part join ",
    "Hood edge join",
    "Hood edge topstitch",
    "Hood  upper part join finish ",
    "Hood hem",
    "Loop tack at hood inside & mouth close",
    "V make",
    "Mark for hood attach",
    "Hood tack to body ",
    "Hood attach",
    "Front neck topstitch",
    "Back neck tape attach",
    "Main label mark & atatch",
    "Back neck tape close with loop",
    "Care lbl make & attach",
    "Armhole topstitch",
    "Flag label attach",
    "Side seam  ",
    "Sleeve cuff join & fold ",
    "Sleeve cuff inside tack",
    "Sleeve cuff attach",
    "Sleeve cuff topstitch",
    "Bottom rib join,fold ,mark & body mark",
    "Bottom rib inside tack",
    "Bottom rib servicing & mark",
    "Bottom rib attach ",
    "Bottom rib topstitch",
    "Sleeve & bottom join tack",
    "Country label attach",
    "Spot & sticker remove",
    "Pocket edge ol 1st & 2nd",
    "Mark for pocket attach",
    "Batack at pocket & over stitch open",
    "Hood  upper & lower two part join ",
    "Hood  upper two part join  topstitch",
    "Punch for hole",
    "Hole at hood with fusing",
    "Bottom rib join,fold mark & body mark",
    "Drawcord middle tack ",
    "Tack for hood hem"
  ]
};

function CAScrollDown({getDropdownValue}) {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState("Tee");
  const [items, setItems] = useState([
    { label: "Tee", value: "Tee" },
    { label: "Polo", value: "Polo" },
    { label: "Sweat Shirt", value: "Sweat Shirt" },
    { label: "Jacket", value: "Jacket" },
    { label: "Trouser", value: "Trouser" }
  ]);

  const [processOpen, setProcessOpen] = useState(false);
  const [processValue, setProcessValue] = useState([]);

  const [process, setProcess] = useState(
    styleWiseProcess[value].map((e) => ({ label: e, value: e }))
  );

  const onChange = (value) => {
    setProcessOpen(false);
    setProcess(styleWiseProcess[value].map((e) => ({ label: e, value: e })));
  };

  const onChangeProcess = (processValue) => {
    getDropdownValue(value, processValue)
  }

  return (
    <View>
      <View style={styles.dropdown}>
        <View style={{zIndex: 100}}>
          <DropDownPicker
            style={styles.dropdown1}
            dropDownContainerStyle={{ width: "100%"}}
            listItemContainerStyle={{}}
            open={open}
            value={value}
            items={items}
            setOpen={setOpen}
            setValue={setValue}
            setItems={setItems}
            onChangeValue={onChange}
            dropDownDirection="BOTTOM"
            listMode="FLATLIST"
          />
        </View>
        <View>
          <DropDownPicker
            style={styles.dropdown2}
            dropDownContainerStyle={{ width: "50%", marginTop: 20 }}
            listItemContainerStyle={{}}
            open={processOpen}
            value={processValue}
            items={process}
            setOpen={setProcessOpen}
            setValue={setProcessValue}
            setItems={setProcess}
            dropDownDirection="BOTTOM"
            listMode="MODAL"
            modalTitle="Select Process from Below List"
            modalProps={{ animationType: "fade" }}
            placeholder="Select Process"
            onChangeValue={onChangeProcess}
          />
        </View>
      </View>
    </View>
  );
}

export default CAScrollDown;

const styles = StyleSheet.create({
  dropdown:{
    flexDirection: 'row',
  },
  dropdown1:{
    width: screenWidth * 0.25,
    backgroundColor: "#f8f9fa"
  },
  dropdown2:{
    width: screenWidth * 0.75,
    backgroundColor: "#f8f9fa"
  },
  hourInput: {
    flexDirection: "row"
    // marginLeft:screen_width * 0.05,
  },
  textInput: {
    width: "30%",
    // height: 30,
    borderWidth: 2,
    borderColor: "black",
    borderRadius: 5,
    textAlign: "center"
  }
});